### ISSUE TITLE
Пароль

### ISSUE THREAD

**Issue by Lui22** [rrrrs09/monitor#1]
Брат, если чо, мы случайно увели твой акк. Если надо, напиши на Leorybalov@yandex.by -- мб отдадим страницу

**Comment by Lui22** [comment]
@rrrrs09 оно тут так работает, не?

**Comment by rrrrs09** [comment]
> Брат, если чо, мы случайно увели твой акк. Если надо, напиши на [Leorybalov@yandex.by](mailto:Leorybalov@yandex.by) -- мб отдадим страницу
